CIのエラーを検知できるようにしました

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -68,11 +68,26 @@ jobs:
           path: tests
 
       - name: Run tests
-        shell: bash
-        run: find tests -type f -perm 0755 -print -exec {} \; 2>&1 | tee result.txt
         continue-on-error: true
+        shell: bash
+        # language=bash
+        run: |
+          find tests -type f -perm 0755 \
+            -print \
+            -exec {} \; 2>&1 | \
+          tee --append result.txt
 
       - name: Remove artifacts
         uses: geekyeggo/delete-artifact@v5
         with:
           name: all-tests
+
+      - name: Result
+        shell: bash
+        # language=bash
+        run: |
+          if grep -q 'FAIL' result.txt; then
+            echo "Test Failed" >> /dev/stderr
+            cat result.txt >> /dev/stderr
+            exit 1
+          fi
